"""updated user product

Revision ID: d38c4fe6ae86
Revises: b0e09f0c77fc
Create Date: 2022-07-13 09:22:01.815667

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "d38c4fe6ae86"
down_revision = "b0e09f0c77fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
